### ISSUE TITLE
Documentation Outline

### ISSUE THREAD

**Issue by jarradh** [status-im/docs.status.im#5]
look through https://github.com/PharkMillups/beautiful-docs or other documentation and maybe come up with some suggestions on the best 'outline' or layout for developers

we need things like Intro, Quickstart, Getting Started with HTML5 Dapps, Getting Started with Chatbots, this sort of thing

**Comment by AKhoriaty** [comment]
Two great reads on how to style and write good docs
http://blog.parse.com/learn/engineering/designing-great-api-docs/
https://jacobian.org/writing/what-to-write/

My favorite example from the list is https://dev.twitter.com/docs 

I'll summarize what I read with a constructed doc template below. **Keep in mind this is just a quick template. The best docs are hand crafted for their specific audience and purpose, and we'll be doing the same with Status docs.**


# [Introduction]
_The introduction title serves as a title for the entire section therein. For example, "Status Chatbot API". Below the intro header, a small paragraph may be used to explain what this section is, and why it's relevant._

# Overview
_The overview should be a short summary (bullet points, list, or table if possible) of the following section of the docs. It's like an abridged table of the doc's contents, but can also contain other reading or dependencies that need to be discoverable in order to understand this section._

# Quickstart
_This is where the magic happens. Readers that can come away from the quickstart successfully are far more likely to come back to the advanced section for more._

> The goal of the quickstart is to walk the user through the minimal steps needed to do the smallest thing possible in your API. Nothing more. 

_A good quickstart should be achievable in under 30 minutes._

-----------------------------------------------------------------------------
At this point, it should be safe to assume the following:
1. The reader has completed at least one example, and knows what they're in for
2. The reader has a small idea of what's possible, and have been given an organic desire to move on
3. The reader has access to any dependent or external resources with a single click

With these 3 things in mind, we can dive into more advanced documentation of specific facets of the API. Transitioning from easier tutorials covering basic, frequently used end points into more detailed reference material for each available end point should establish a flow that allows readers to go as far as they need to get the job done, and come back later for anything they're missing.

The most important thing to remember for any deeper dive is to **include examples**. 

-----------------------------------------------------------------------------

# [Getting Started with ___ ] 
_Opening up each advanced section with another quick overview of what will be covered may be necessary depending on the length._ 

## [Tutorial 1 - Common endpoints]
_Be sure to break any coding examples up into small enough pieces so that the reader can follow along. Include explanations of how the example is progressing as you go - this doesn't need to be step-by-step, but should include enough explanation to not leave them guessing._
## [Tutorial 2 - Common endpoints]
_Same as above_

As you lay the foundation for understanding the more common endpoints in the API, start extending these examples to touch on the more specialized endpoints.

## [Tutorial 3 - Less common endpoints]
_Again, try to make this example extend upon examples in the above tutorials. Show users how to do something cooler than making something that "just works"_
## [Tutorial 4 - Less common endpoints]
_Same as above_

Guiding the reader beyond this point requires less structure. It's safe to assume that anyone seeking the "nitty gritty" information on the rarer endpoints will be highly motivated to find that specific information. Make it "available", but not necessarily "easy". 

## [Reference - Advanced endpoints]
_Every endpoint discussed should come with at least one example. It's not necessary to have these examples extend from above tutorials, so long as the form and function is clearly shown._

------------------------------------------------------------------------------------------------

That's all for now. Modularizing each piece of the documentation puzzle to fit together is not a task that can be summarized, but using this as a starting point should set us up for a much easier go at that.
